In [4]:
import numpy as np 
npa= np.array([1, 2, 3])
print(npa)

[1 2 3]


In [5]:
import numpy as npp
a = npp.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
import numpy as np
x=np.zeros(3)
print(x)

[0. 0. 0.]


In [12]:
import numpy as np
x=np.ones(3)
print(x)

[1. 1. 1.]


In [14]:
import numpy as np
ab=np.empty(3)
print(ab)

[1. 1. 1.]


In [15]:
import numpy as np
n=np.arange(10)
print(n)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
import numpy as np
a=np.arange(1,20,4)
print(a)

[ 1  5  9 13 17]


In [20]:
x = np.ones(4, dtype=int)
print(x)
x

[1 1 1 1]


array([1, 1, 1, 1])

In [25]:
ar = np.array([16, 21, 43, 4, 35, 61, 17, 28, 91, 10])
print(ar)
ar=np.delete(ar, 4)
print(ar)
ar=np.sort(ar)
print(ar)

[16 21 43  4 35 61 17 28 91 10]
[16 21 43  4 61 17 28 91 10]
[ 4 10 16 17 21 28 43 61 91]


In [26]:
import numpy as np

a = np.array(1)
b = np.array([10, 20, 30, 40, 50])
c = np.array([[11, 22, 33], [44, 55, 66]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)
print("dimension= ", a.ndim)
print(b)
print("dimension= ", b.ndim)
print(c)
print("dimension= ", c.ndim)
print(d)
print("dimension= ", d.ndim)


1
dimension=  0
[10 20 30 40 50]
dimension=  1
[[11 22 33]
 [44 55 66]]
dimension=  2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dimension=  3


In [27]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4]])

print(arr.shape) 

(3, 4)


In [30]:
a = np.arange(9)
print(a)

b = a.reshape(3,3)
print(b)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
import numpy as np

a=np.array(50)
b=np.array([10,20,30])

add= np.add(a,b)
sub=np.subtract(b,a)
mul=np.multiply (a,b)
div=np.divide (b,a)
div1=np.divide (b,10)

print("Print A= ",a)
print("Print B= ", b)
print("After Addition =", add)
print("After Subtraction =",sub)
print("After Multiplcation =",mul)
print("After Division =",div)
print("After Division =",div1)

Print A=  50
Print B=  [10 20 30]
After Addition = [60 70 80]
After Subtraction = [-40 -30 -20]
After Multiplcation = [ 500 1000 1500]
After Division = [0.2 0.4 0.6]
After Division = [1. 2. 3.]


In [33]:
n= np.array([0.25,0.50,0.75,1.0,1.25])
print(n)

rec=np.reciprocal(n) 
print(rec)

[0.25 0.5  0.75 1.   1.25]
[4.         2.         1.33333333 1.         0.8       ]


In [36]:
a=np.array([5,10,15])

print(a)

pow=np.power(a,4)
print("after ^4 = ", pow)


b=np.array([3,2,1])

pow1=np.power(a,b)
print("after b array elements as ^ = ", pow1)

[ 5 10 15]
after ^4 =  [  625 10000 50625]
after b array elements as ^ =  [125 100  15]


In [37]:
a= np.array ([1,3,5])
b= np.array ([2,4,6])

print("values of A=", a)
print("values of B=", b)

mm=np.mod(a,b)
rm=np.remainder(a,b)

print("values of MOD=", mm)
print("values of REMAINDER=", rm)

values of A= [1 3 5]
values of B= [2 4 6]
values of MOD= [1 3 5]
values of REMAINDER= [1 3 5]


In [38]:
a=np.array([-5.6j, 0.2j,11, 1+1j])
print(a)

print("real=",np.real(a))
decimal 
print("imaginary=",np.imag(a))

print("Conjugate=", np.conj(a))

[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]
real= [-0.  0. 11.  1.]
imaginary= [-5.6  0.2  0.   1. ]
Conjugate= [-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


In [41]:
a=np.array ([1.0562,5.32345,123.9823,0.5645,25.52223,32.9952])

print(a)

print("after rounding up=", np.around(a))

print("after rounding up to 3rd decimal value =", np.around(a,decimals=3))

[  1.0562    5.32345 123.9823    0.5645   25.52223  32.9952 ]
after rounding up= [  1.   5. 124.   1.  26.  33.]
after rounding up to 3rd decimal value = [  1.056   5.323 123.982   0.564  25.522  32.995]


In [43]:
a=np.array ([1.0,-5.3,123,-0.56,25.5,32])

print(a)

print('\n')
print(np.around(a))

print(np.floor(a))

print(np.ceil(a))

[  1.    -5.3  123.    -0.56  25.5   32.  ]


[  1.  -5. 123.  -1.  26.  32.]
[  1.  -6. 123.  -1.  25.  32.]
[  1.  -5. 123.  -0.  26.  32.]
